# Generated by Django 5.1.4 on 2024-12-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=45)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_successful", models.BooleanField()),
                ("min_latency", models.FloatField(null=True)),
                ("avg_latency", models.FloatField(null=True)),
                ("max_latency", models.FloatField(null=True)),
                ("packet_loss", models.FloatField(null=True)),
                ("packets_transmitted", models.IntegerField(null=True)),
                ("packets_received", models.IntegerField(null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
